apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jpj9wg12x-go 
  janus-idp.io/tekton: jpj9wg12x-go
  backstage.io/kubernetes-id: jpj9wg12x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jpj9wg12x-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  