apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jpj9wg12x-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:28d1d0c53497305e3fc73eaac5760fa76ecf4848@sha256:738ba03008cf10934e89deaecd05a6f5427b9785bd8f29e6c7904d062165d719
          name: container-image
